### ISSUE TITLE
bug of the steps 5

### ISSUE THREAD

**Issue by cindy12-gao** [lahammond/BrainJ#10]
I ran the step 5 according to the manual, but there is a error of the file format.
![error 1](https://user-images.githubusercontent.com/72720700/172745639-fabccc1a-a3d1-45d6-8c10-510f282de7cc.PNG)
![二row](https://user-images.githubusercontent.com/72720700/172745679-ec3b4883-5ff0-403f-b67d-6740ee032fd4.PNG)

**Comment by lahammond** [comment]
Hi Cindy,
Are you still having issues with this? It's not something I have seen before. 
The initial step in the pipeline standardizes the data, and provided you are using the provided ilastik project (and modifying based on the pdf guide) there shouldn't be any issues with data generated further on in the pipeline.
Are you running the pipeline using the provided Ilastik project?

**Comment by cindy12-gao** [comment]
hi, the error still occured. I saved the ilastik project and set the export file format as .tiff or .tif, and named as  Ilastik_Project_Channel_3.ilp. the cell number counting can be processed, but the projection analysis always has the error information like the picture
![error2](https://user-images.githubusercontent.com/72720700/178388112-a2358a66-cc67-4413-b7da-b94ca09656cc.JPG)
![TISS](https://user-images.githubusercontent.com/72720700/178388215-2c37989c-2b72-49c4-9aaa-956dc854c737.JPG)
![projection error](https://user-images.githubusercontent.com/72720700/178388243-482f336d-bd13-4564-8d6d-a894ea3ec4c6.JPG)
![3](https://user-images.githubusercontent.com/72720700/178388268-53f026f9-d53d-4c48-9307-b18e08c847b8.JPG)
.

**Comment by lahammond** [comment]
Hi Cindy,

I haven't seen these issues before - it looks to be related to the files being generated by Ilastik. These should be fine if you use the provided Ilastik file, and update the raw data and training (see youtube workshop and pdf) - but issues can occur if you create a new ilastik file as there are settings within the ilastik file that ensure compatibility.

Best,

Luke
