### ISSUE TITLE
question of the isolated region

### ISSUE THREAD

**Issue by cindy12-gao** [lahammond/BrainJ#11]
Hi,
  in the first step set experiment parameter, there is a analysis type-isolated region,  can it do the registration of isolated brain area, like isolated hippocampus?
![demo](https://user-images.githubusercontent.com/72720700/176144753-36e20178-0215-4028-b330-b77ee5d0043c.JPG)

**Comment by lahammond** [comment]
Hi Cindy,
No, this feature is not presently available.
