### ISSUE TITLE
Another bug of step 5 

### ISSUE THREAD

**Issue by JinyunWuu** [lahammond/BrainJ#12]
I am sorry but when I am running step 5, the atlas registration failed and this bug occurred. Is there anything wrong with my parameter settings? 
![捕获1](https://user-images.githubusercontent.com/46867235/178634689-147d553d-148c-46c5-8e25-ba019ad9dd29.PNG)

**Comment by lahammond** [comment]
HI Jinyun,

Thanks for reaching out.

It looks like the dataset you are working with might be too small to successfully register to the 3D template brain. For alignment, the dataset does not need to be an entire brain but should be complete for the range it is covering (no missing sections unaccounted for), and span at least 1.5mm in the Anterior-Posterior axis. If there are issues with section quality, then at least 2.5mm is required.
It's also worth checking that the dataset used for alignment looks OK - Dataset\3_Registered_Sections\DAPI_25.tif.
Open this file along with the ABA template file (e.g. ABA_CCF_25_2017\template.tif) and confirm they are scaled similarly.

There are also some useful notes on the pipeline in the pdf guide.

I hope this helps!

**Comment by JinyunWuu** [comment]
Thank you very much. It really helps!

**Comment by JinyunWuu** [comment]
Thank you very much. It really helps!
