### ISSUE TITLE
How to automatically detect tissue (slices) from slide?

### ISSUE THREAD

**Issue by Virginia9733** [lahammond/BrainJ#13]
Hi there,

Thank you so much for developing this toolbox.
I am trying the use BrainJ to see the brain-wide projection.
But I encounter the problem of detecting slices from slide imaging. Is there a way to automatic detect and extract slices from slides？
![Screenshot 2023-03-26 212532](https://user-images.githubusercontent.com/61534754/227775488-b1ca4791-e76e-4f31-b604-91eedb9a0cac.png)

Another issue is that the slide scanner we use does not automatically merge different channels into a tiff. If that's the case, should I merge them together, or does the overlay of different channels still work?

Looking forward to hearing from you!

**Comment by lahammond** [comment]
Hi Virginia,

Apologies for the delayed response, I missed the notification about this issue.
BrainJ doesn't include a tool for cropping sections from whole slide images. One tool that may be suitable is SlideCrop (https://github.com/QBI-Microscopy/SlideCrop_v2). The sections on this slide are very close to each other, though, so you may wish to space the sections further apart to facilitate automatic detection and extraction.
BrainJ expects each section to be a single file (which can contain multiple channels). If your channels are in separate files, combining them into a single tif first using a macro or script would allow you to process them in BrainJ. 

I hope this helps!
