### ISSUE TITLE
Registration throw an "empty array" error

### ISSUE THREAD

**Issue by 7heRedFox** [lahammond/BrainJ#5]
When launching the registration step with only the registration ticked, the macro return the following error:
![image](https://user-images.githubusercontent.com/48990624/143861164-70d08f31-9d36-4a25-95ea-68884e4d0bbc.png)

Is there something to update so I don't have this issue anymore, it seems to have problem opening the image

For my image I have my fluorescent dye on ch1 and my Nissl on ch2 and here is the setup file :
`Parameter,Value`
`Directory:,C:\Users\gusseglio\Desktop\BrainJ Template\1.Examples`
`Reference section:,1`
`Peform Second Pass Reg?,1`
`Full resolution DAPI,1`
`Cell Resolution:,0`
`Cell Detection Type:,Machine Learning Segmentation with Ilastik`
`Cell Analysis 1:,2`
`Cell Analysis Cell SizeC1:,20`
`Maxima Int 1:,200`
`Cell Analysis 2:,0`
`Cell Analysis Cell SizeC2:,20`
`Maxima Int 2:,100`
`Cell Analysis 3:,0`
`Cell Analysis Cell SizeC3:,15`
`Maxima Int 3:,30`
`Cell Analysis BG Subtraction:,7`
`Cell Analysis US Mask:,0`
`Cell Analysis US Mask Weight:,0`
`Intensity Validation:,0`
`Projection Detection Type:,Machine Learning Segmentation with Ilastik`
`Projection Analysis 1:,1`
`Projection Analysis 2:,0`
`Projection Analysis 3:,0`
`Projection Min Intensity 1:,70`
`Projection Min Intensity 2:,70`
`Projection Min Intensity 3:,70`
`Projection ResolutionXY:,10`
`Projection Resolution Zsection:,25`
`Ilastik:,C:\Program Files\ilastik-1.3.3post3`
`Elastix:,C:\Program Files\Elastix5.0.0`
`Atlas Type:,25um template brain`
`Trim:,15`
`BrainJ Version:,97`

[Analysis_Settings.csv](https://github.com/lahammond/BrainJ/files/7617910/Analysis_Settings.csv)

**Comment by lahammond** [comment]
Running registration only as you have here shouldn't cause an issue. 
The pipeline is looking for the data from the previous step - have you run "2 Reformat Sections"?
