### ISSUE TITLE
Some problems of the step5, atlas registration

### ISSUE THREAD

**Issue by cindy12-gao** [lahammond/BrainJ#7]
hi, there some problems of the step of atlas registration .
the log file below:
itk::ExceptionObject (000000C44B15F380)
Location: "ElastixTemplate - Run()" 
File: f:\x\src\elx\elastix\components\imagesamplers\randomcoordinate\elxRandomCoordinateSampler.hxx
Line: 113
Description: itk::ERROR: RandomCoordinateSampler(000002078096FE30): ERROR: in your parameter file you selected
  SampleRegionSize[ 2 ] = 100 mm,
  while the fixed image size at dim = 2 is 18 voxels or 18 mm.
  Please select a smaller SampleRegionSize!
  It is recommended to be not larger than 1/3 of the image size in mm.

**Comment by cindy12-gao** [comment]
@lahammond

**Comment by cindy12-gao** [comment]
actually, I`m little confused with the definition of dim2, and sample regionsize. Is the parameter means the slice section thickness?  I saw the you used 5 slice can also make the registration successfully in the video, But i made the error using 6 slices. do you know the reason ?

**Comment by lahammond** [comment]
Thanks for reaching out.
It looks like the dataset you are working with is too small to successfully register to the 3D template brain. For alignment, the dataset does not need to be an entire brain but should be complete for the range it is covering (no missing sections unaccounted for), and span at least 2mm in the Anterior-Posterior axis.
I hope this helps!

**Comment by cindy12-gao** [comment]
Thank you for your reply.
So do I need to prepare more data slices from olfactory bulb to cerebellum ？





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：Luke ***@***.***>
日　期：2022年05月16日 23:44:21
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [lahammond/BrainJ] Some problems of the step5, atlas registration (Issue #7)

Thanks for reaching out.
 It looks like the dataset you are working with is too small to successfully register to the 3D template brain. For alignment, the dataset does not need to be an entire brain but should be complete for the range it is covering (no missing sections unaccounted for), and span at least 2mm in the Anterior-Posterior axis.
 I hope this helps!

**Comment by cindy12-gao** [comment]
And I saw your demo in the video, there were only 5 slices, did they can registered successfully?





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：Luke ***@***.***>
日　期：2022年05月16日 23:44:21
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [lahammond/BrainJ] Some problems of the step5, atlas registration (Issue #7)

Thanks for reaching out.
 It looks like the dataset you are working with is too small to successfully register to the 3D template brain. For alignment, the dataset does not need to be an entire brain but should be complete for the range it is covering (no missing sections unaccounted for), and span at least 2mm in the Anterior-Posterior axis.
 I hope this helps!

**Comment by lahammond** [comment]
Yes, you would need to include more slices to make up at least 2mm spanning the AP axis.

I would have used only a few sections as an example for this step in the live demonstration to save time. For the final 3D alignment to the template we used a larger volume. Apologies for any confusion. The best resource for troubleshooting the pipeline is the pdf guide. https://github.com/lahammond/BrainJ/blob/master/BrainJ%20Guide%209_3.pdf
