### ISSUE TITLE
some confused questions about step2

### ISSUE THREAD

**Issue by cindy12-gao** [lahammond/BrainJ#8]
hello, I feel uncertaion about step2. the step2 can process each section is centered and made horizontal in the image frame, is there the procedure about ranking? actually ,  I named the slices by number according the slice order, but the results about the order was wrong
![Capture](https://user-images.githubusercontent.com/72720700/169192671-a71ee210-2558-4cd2-a7b5-9714f9743af7.PNG)
.

**Comment by lahammond** [comment]
Hi Cindy,

Thanks for sharing the image.

Could you check the way the sections were named? The ections must be named alphanumerically in an anterior to posterior order (e.g. Section001, Section002... Section009, Section010... ). Be careful not to use a numbering system that may place sections out of order (e.g. Section1, Section2... Section9, Section10...).  -- it's possible your naming system may be like that later.

Also, in step 1, when setting the Experiment Parameters, ensure the "File Order" is set to "alphanumeric".

I hope this helps.

**Comment by cindy12-gao** [comment]
yes, your judgement is right, I`ve change the name series, like your mentioned. and now the order is right. Thank you~
