### ISSUE TITLE
Problems on the step of  create IIastik training Images

### ISSUE THREAD

**Issue by cindy12-gao** [lahammond/BrainJ#9]
Hi, after the registration successfully, I want to detect the signal of cell
I define the parameter of training like thi
![define](https://user-images.githubusercontent.com/72720700/170621859-32d9c9e5-4bf3-4c81-8bbf-87cf4d715d5c.PNG)
s
I select the folder1--reformatted-Sections   and the channel 2

but when I ran, there is the error
![bug](https://user-images.githubusercontent.com/72720700/170622042-0282757f-893f-4ec3-9086-8d18279d64a5.PNG)

I don`t know why,  hope for your answer

**Comment by lahammond** [comment]
Hi Cindy,

When you run any of the steps in the pipeline, select the main dataset folder, not the subfolders. 
It looks like you are selecting the "Reformatted Sections" subfolder - you should run this step on the "name_slice" folder.

I recommend using the pdf guide as you work through the pipeline as it will help you avoid any issues:
https://github.com/lahammond/BrainJ/blob/master/BrainJ%20Guide%209_3.pdf
